\restrict hpfhfCLvJW5LEjDYgRTxLUGgI6eji5E9HuB2xk2Eo1WMcFCH9ImvmVLaZeUnkBG
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
CREATE TYPE public.collection_type AS ENUM (
    'places',
    'cities'
);
SET default_tablespace = '';
SET default_table_access_method = heap;
CREATE TABLE public.article_photos (
    id integer NOT NULL,
    article_id integer NOT NULL,
    url text NOT NULL,
    description text,
    "position" integer DEFAULT 1
);
ALTER TABLE public.article_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_photos_id_seq
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.article_tags (
    article_id integer NOT NULL,
    tag_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.articles (
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    updateddate date NOT NULL,
    text text NOT NULL,
    visibility boolean DEFAULT true NOT NULL
);
ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.cities (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    updateddate date,
    article text,
    country_id integer NOT NULL,
    visibility boolean DEFAULT true NOT NULL
);
ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
    START WITH 21
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.city_photos (
    id integer NOT NULL,
    city_id integer NOT NULL,
    url text NOT NULL,
    description text,
    "position" integer DEFAULT 1
);
ALTER TABLE public.city_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.city_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.city_tags (
    city_id integer NOT NULL,
    tag_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.collection_cities (
    collection_id integer NOT NULL,
    city_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.collection_places (
    collection_id integer NOT NULL,
    place_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.collection_tags (
    collection_id integer NOT NULL,
    tag_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.collections (
    id integer NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    type public.collection_type NOT NULL,
    updateddate date NOT NULL,
    visibility boolean DEFAULT true NOT NULL
);
ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.countries (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    visibility boolean DEFAULT true NOT NULL,
    description text,
    updateddate date,
    article text
);
ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 10
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.country_tags (
    country_id integer NOT NULL,
    tag_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.place_photos (
    id integer NOT NULL,
    place_id integer NOT NULL,
    url text NOT NULL,
    description text,
    "position" integer DEFAULT 1
);
ALTER TABLE public.place_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.place_tags (
    place_id integer NOT NULL,
    tag_id integer NOT NULL,
    "position" integer NOT NULL
);
CREATE TABLE public.places (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    loc text,
    rate numeric(2,1),
    description text,
    updateddate date NOT NULL,
    city_id integer NOT NULL,
    article text,
    visibility boolean DEFAULT true NOT NULL,
    CONSTRAINT places_rate_check CHECK (((rate IS NULL) OR ((rate >= 1.0) AND (rate <= 5.0))))
);
ALTER TABLE public.places ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.places_id_seq
    START WITH 20
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.tags (
    id integer NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    text_color text DEFAULT '#B46D0A'::text NOT NULL,
    bg_color text DEFAULT '#FDF4E2'::text NOT NULL
);
ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
COPY public.article_photos (id, article_id, url, description, "position") FROM stdin;
1	1	a.1.1.jpg		1
2	2	a.2.1.jpg		1
\.
COPY public.article_tags (article_id, tag_id, "position") FROM stdin;
\.
COPY public.articles (id, name, description, updateddate, text, visibility) FROM stdin;
1	Что такое хайкинг?	Хайкинг — это не просто прогулка, а мировой феномен, объединяющий миллионы людей в стремлении к свободе, здоровью и красоте природы. В этой статье вы узнаете, что такое хайкинг, почему он так популярен, полезен ли он с точки зрения науки, что нужно для начала, и подойдёт ли он именно вам.	2025-08-29	##Простыми словами.\n\nХайкинг — это пешая прогулка по природе: тропы, леса, холмы или горы. В отличие от прогулки по городу, у хайкинга чаще есть цель — сменить обстановку, побыть наедине с природой и слегка выйти из зоны комфорта. Маршрут может занимать пару часов или включать ночёвку. Слово *hike* пришло из XVIII века и сначала означало «подъём», но сейчас это про движение, тишину и ощущение живого тела.\n\n##Почему хайкинг завоевал весь мир?\n\nПо данным *Statista*, в 2023 году более 59 миллионов американцев регулярно ходили в хайкинг — почти каждый пятый. Популярность растёт и в других регионах: люди устали от экранов и стали ценить простую прогулку на свежем воздухе. После COVID спрос особенно вырос — не нужны дорогие билеты, только хорошие ботинки и дорога под ногами.\n\n##Научный взгляд: что даёт хайкинг телу и мозгу.\n\nХайкинг прокачивает и тело, и голову:\n\n* Пешие походы снижают риск сердечно-сосудистых заболеваний примерно на 31% (*Harvard Medical School*).\n* 20–30 минут в лесу уменьшают уровень кортизола почти на 20% (*Frontiers in Psychology*, 2019).\n* Хайкинг повышает выработку эндорфинов, улучшает память и снижает тревожность и депрессию.\n* Это отличное кардио — 300–600 ккал в час в зависимости от рельефа и темпа.\n\nИ всё это — без абонементов, в компании сосен и неба.\n\n##Нужно ли готовиться, или можно просто выйти и пойти?\n\nНачать легко: не требуются особые навыки. Оценивайте силы трезво — начните с 5–7 км по знакомой местности без резких подъёмов. Хайкинг не про героизм, а про удовольствие от движения и природы. Если захочется вернуться — значит, всё правильно.\n\n##Хайкинг для всех?\n\nХайкинг доступен почти каждому: дети, пожилые — всё зависит от маршрута. Подходящая дистанция и рельеф делают его безопасным даже для людей с хроническими заболеваниями; врачи иногда рекомендуют прогулки на природе для улучшения состояния. Главный барьер — лень. Но один выход на тропу и желание повторить обычно побеждают её.\n\n##Что взять с собой?\n\nНе экспедиция, но подготовиться стоит:\n\n* Удобная обувь (кроссовки или лёгкие треккинговые ботинки).  \n* Вода — минимум литр на пару часов, лёгкий перекус (орехи, банан).  \n* Ветровка/дождевик, аптечка с пластырями и антисептиком.  \n* Телефон с офлайн-картой или компас.  \n* Солнцезащитный крем и кепка при открытом маршруте.\n\n##С чего начать?\n\nПосмотрите вокруг: лес, река или длинная петля в парке подойдут. Наденьте удобную обувь, соберите рюкзак и выйдите — в одиночку или с другом, с плейлистом или без. Сначала может показаться обычной прогулкой, но со временем станет привычкой — и вы вернётесь домой спокойнее и собраннее.	t
2	Почему солнцезащитный крем (SPF) — ваш лучший друг.	Всё, что нужно знать о солнцезащите: почему ультрафиолет вреден, как работает SPF, зачем пользоваться кремом даже зимой и как выбрать средство под свою кожу и образ жизни.	2025-08-29	## Зачем нам защита от солнца\n\nСолнце приятно греет кожу, но его лучи не так безобидны. UVA проникают глубоко и разрушают коллаген, ускоряя появление морщин и пигментации. UVB — те самые, что вызывают ожоги и могут повреждать ДНК. Со временем это повышает риск рака кожи и старит её быстрее, чем нам хотелось бы.\n\n## Почему крем нужен круглый год и даже под тучами\n\nМногие думают: если не жарко и небо затянуто облаками, крем можно пропустить. Но облака пропускают до 80 % ультрафиолета, а зимой снег отражает до 85 % лучей. Даже асфальт и стены домов возвращают часть излучения. Поэтому солнцезащита нужна не только летом и на пляже, но и в городе, и в морозный день.\n\n## Понятно о сложных вещах: SPF, PA и всё такое\n\nSPF — это показатель защиты от ожогов: SPF 30 значит, что кожа будет защищена примерно в 30 раз дольше. PA отвечает за защиту от UVA-лучей, виновников старения кожи: чем больше плюсов рядом с буквами, тем надёжнее барьер.  \n\nВыбор зависит от вашей кожи. Жирной подойдут лёгкие гели и флюиды без масел. Сухой — средства с гиалуроновой кислотой или глицерином. Чувствительной — минеральные фильтры на основе цинка или диоксида титана. В городе достаточно SPF 25–30, а вот для моря или похода лучше взять водостойкий SPF 50+ в удобном формате — спрей, стик или компакт.\n\n## Как крем превращается в спасителя кожи\n\nЧтобы крем подействовал, нанесите его за 15 минут до выхода из дома. На лицо и шею хватит примерно чайной ложки средства. Не забудьте про уши и линию роста волос. Обновляйте слой каждые два–три часа, особенно если двигаетесь активно или купаетесь. А вечером важно смыть крем полностью: сначала гидрофильным маслом или бальзамом, потом привычной пенкой или гелем.\n\n## Найдите свой идеальный крем\n\nКрем должен подходить именно вам. Жирной коже будет комфортнее с лёгкими текстурами, сухой — с увлажняющими формулами, а чувствительной — с минеральной защитой. И смотрите на образ жизни: если вы в городе, достаточно лёгкого SPF 25–30. Для активного отдыха нужен надёжный водостойкий SPF 50+, который удобно обновлять прямо в пути.\n\n## Мифы\n\nСуществует немало заблуждений. SPF не мешает загорать — он лишь делает процесс более безопасным и ровным. Тональный крем с SPF, к сожалению, не заменяет полноценную защиту: его нужно наносить слишком толстым слоем, чтобы получить реальную защиту. А смуглая кожа хоть и имеет небольшой естественный барьер, но этого всё равно мало, чтобы часами находиться под солнцем без вреда.\n\n## Выводы\n\nSPF нужен каждому. Это не каприз и не модный тренд, а простая забота о здоровье кожи. Достаточно включить солнцезащиту в свой ежедневный уход — и вы уже защищаете себя от преждевременных морщин и других неприятных последствий. Главное — без фанатизма, но регулярно.	t
3	Как не заблудиться в лесу и горах: правила безопасности		2026-08-16		t
\.
COPY public.cities (id, name, description, updateddate, article, country_id, visibility) FROM stdin;
1	Санкт-Петербург	\N	2025-07-03	\N	1	t
2	Астана	Город будущего посреди бескрайней казахской степи. Здесь есть здания в форме яиц, пирамид и шатров, зеркальные фасады и небоскрёбы, отражающие небо. Он создан с нуля — как эксперимент, как смелая идея. Утопия, где можно увидеть, каким может стать мегаполис, если дать архитекторам полную свободу. И всё же в этой футуристике чувствуется восточная философия и простор.	2025-07-03	\N	6	t
3	Ереван	Город, который старше Рима, но по ощущениям – молодой и домашний. Утро начинается с аромата кофе и хачапури, вечер — с панорамы на заснеженный Арарат. Розовый туф придаёт улицам тёплый оттенок заката, а радушие жителей превращает простую прогулку по Каскаду в душевное путешествие. Это место, где история живёт не в музеях, а в каждом жесте, слове и взгляде.	2025-07-03	\N	3	t
4	Батуми	Черноморский курорт, где можно плавать утром, гулять в горах днём и танцевать под дождём вечером. Современные здания в виде книг и башен с часами, пальмы на бульварах, хачапури по-аджарски, поданный на фоне заката — всё это делает город живым и немного сюрреалистичным. Море здесь не просто фон — оно часть городской души.	2025-07-03	\N	5	t
5	Тбилиси	Город с запахом вина, серных источников и истории. Здесь всё немного криво, разноцветно и очаровательно: деревянные балконы висят над обрывами, узкие улочки ведут в неожиданные дворики, где за ужином могут пригласить даже прохожего. В Тбилиси одновременно уютно, как у бабушки, и дерзко, как у уличного художника. В нём невозможно не влюбиться.	2025-07-03	\N	5	t
6	Баку	Город ветров и пылающих небоскрёбов, расположенный на берегу Каспия. Здесь рядом стоят древние стены Старого города и ультрасовременные «Пламенные башни». Уютные улочки с коврами, азербайджанский чай в армуде и разноцветные огни вечернего бульвара создают атмосферу, в которой Восток и Запад не просто соседствуют, а вдохновляют друг друга.	2025-07-03	\N	2	t
7	Сула	Музей под открытым небом, где можно погрузиться в атмосферу старой шляхетской Беларуси. Здесь не просто экскурсия, а настоящее историческое шоу с рыцарями, ремесленниками и фестивалями. Место даёт почувствовать себя гостем прошлых веков.	2025-08-25	\N	4	t
8	Несвиж	Место с особой аристократической аурой, известное своим замковым ансамблем, который входит в список ЮНЕСКО. Здесь оживает история могущественного рода, а ухоженные парки и пруды создают романтическую атмосферу. Отличный вариант для спокойного и красивого отдыха.	2025-08-25	## Цены\n* Съём жилья в день: бюджетные варианты $20–40, отели у замка дороже; в сезон цены поднимаются.\n* Ужин в ресторане: $10–20 на человека (зависит от места).\n\n## На территории или рядом\n* Несвижский замок (Радзивиллов) — объект Всемирного наследия ЮНЕСКО; большой парк и комплекс музея-заповедника.\n* Небольшой городской центр с ратушей, церковью Corpus Christi и парком.\n\n## Транспорт\n* Междугородние автобусы/поезда: из Минска идёт регулярный транспорт.\n* По городу — пешком: большинство достопримечательностей в шаговой доступности.\n\n## Еда\n* Драники и мачанка (традиционные белорусские блюда) — в маленьких городах часто готовят по деревенским рецептам.\n* Местные продукты/выпечка — приятный бонус при прогулке по городу.\n\n## Районы\n* Исторический центр (вокруг замка и ратуши) — туристический и самый интересный.\n* Жилые кварталы вокруг — где люди живут и где можно посмотреть быт города.	4	t
9	Ташкент	Город-контраст, где советский модернизм соседствует с восточными базарами, а широкие проспекты переплетаются с тенистыми улочками. Он шумный, тёплый, и вечно голодный до жизни. Здесь по-прежнему продают лепёшки с маком у метро, а в старом городе слышно азан. Несмотря на высокие здания и автобаны, Ташкент остаётся домом, где каждый может найти свою чайхану.	2025-07-03	\N	9	t
10	Бухара	Живая энциклопедия Востока. В этом городе не просто сохранились памятники — здесь до сих пор чувствуется дыхание караванов и шелеста шёлковых одежд. Минареты, медресе и базары создают ощущение, что ты попал в сказку «1001 ночи». Но при этом всё настоящее: пожилой мастер чеканки, зелёный чай на коврах, дети, играющие у древней стены — здесь всё ещё идёт жизнь.	2025-07-03	\N	9	t
11	Алматы	Самый «европейский» город Центральной Азии, окружённый горами, фруктовыми садами и добродушной суетой. Здесь можно позавтракать в хипстерском кафе, а через полчаса оказаться в горном ущелье. Осенью пахнет яблоками и листьями, зимой — дымом каминов, а летом — горами и мороженым. Это город настроения, который легко меняется, но всегда остаётся тёплым.	2025-07-03	\N	6	t
12	Бишкек	Молодой, раскидистый, немного сонный и очень душевный. Город, где растут тополя, тянутся горы, а с улиц доносится запах самсы и дыни. Тут нет спешки, зато есть ощущение, что всё возможно. Рынки с шелками, скейт-парки, парки с бабушками на скамейках — всё соседствует в тёплой неформальной атмосфере.	2025-07-03	\N	7	t
13	Душанбе	Город, где горы видны из любой точки, а воздух кажется немного слаще. Он не шумный, не вычурный, но в нём есть достоинство. Прогулка по его улицам — это плавное течение мимо деревьев, советских зданий, новых фасадов и восточной мягкости. Это столица, которая не давит, а приглашает присесть, отдохнуть и поговорить.	2025-07-03	\N	8	t
14	Коссово	Небольшой городок с ярким дворцом в неоготическом стиле, который выглядит как настоящий замок из сказки. Архитектура поражает изяществом и необычными формами, а окрестности располагают к неспешному отдыху. Атмосфера словно переносит в другую эпоху.	2025-08-25	\N	4	t
15	Беловежская пуща	Уникальный заповедник, внесённый в список ЮНЕСКО, — одно из немногих мест в Европе, где сохранился первобытный лес. Здесь обитают зубры и множество редких видов животных, а воздух наполнен чистотой и свежестью. Отличное место для эко-туризма и долгих прогулок.	2025-08-25	\N	4	t
16	Лида	Город, где главной доминантой остаётся замок XIV века, сохранивший воинственный облик. Здесь же работает знаменитый завод Лидского пива, продукция которого известна далеко за пределами страны. Атмосфера сочетает средневековую историю и промышленное настоящее.	2025-08-25	\N	4	t
17	Мир	Небольшое местечко, где возвышается величественный замок в стиле ренессанс. Старинная крепость, окружённая прудами и парком, впечатляет своей мощью и романтической красотой. Атмосфера подходит для прогулок и знакомства с легендами прошлого.	2025-08-25	\N	4	t
18	Брест	Пограничный город с особым характером и богатым историческим наследием. Главная гордость — мемориал, связанный с героическими событиями войны, а также знаменитая пешеходная улица с фонарщиком, создающим вечернюю атмосферу. Брест хранит в себе дух старинной Европы и радушие приграничья.	2025-08-25	## Цены\n* Съём жилья в день: ориентировочно $50–100 за стандартный 3-звёздочный номер (всё зависит от даты и места).\n* Ужин в ресторане (средний): 90–120 BYN ($28-37) за ужин на двоих в среднем ресторане.\n\n## На территории или рядом\n* Брестская крепость (главная историческая точка).\n* Беловежская пуща — национальный парк в регионе (выезжают на экскурсии из Бреста).\n\n## Еда\n* Драники (картофельные оладьи) — национальная классика. \n* Мачанка (мясное рагу) с блинами/оладьями.\n\n## Районы\n* Центр / исторический центр (около Советской улицы, пешеходные зоны).\n* Районы у вокзала и жилые спальные районы на окраинах — типичное деление для города.	4	t
19	Минск	Широкий, сдержанный, зелёный. Здесь чувствуется архитектура послевоенной эпохи, монументальность и порядок. Но если заглянуть глубже, город раскрывается: арт-пространства, современное кафе внутри старой фабрики, подземные клубы и уличное искусство. Он не старается понравиться — он просто есть, и в этом его особое спокойствие.	2025-09-21	## Транспорт  \n*Метро: 1 белорусский рубль (около $0.30) за поездку  \n*Автобусы, троллейбусы, трамваи: 0.95 белорусского рубля (около $0.28) за билет, у водителя дороже  \n*Такси: поездка по центру 10-15 белорусских рублей (около $3-5)  \n\n## Еда  \n*Драники: тёртый картофель, обжаренный до золотистой корочки, со сметаной или мясом (около $4-6 за порцию)  \n*Мачанка: густой мясной соус из свинины со шкварками, подаётся с блинами или драниками (около $6-8 за порцию)  \n*Холодник: летний холодный суп из свёклы и кефира с зеленью (около $3-4 за порцию)  \n\n## Районы\n*Центр: проспект Независимости, сталинская архитектура, широкие улицы  \n*Октябрьская улица: граффити, бары, арт-пространства, концерты  \n*Троицкое предместье: старинные домики, набережная, ремесленные лавки  	4	t
20	Гродно	Один из самых живописных городов страны, где сохранились католические и православные храмы, старые кварталы и колоритная застройка. Атмосфера напоминает смесь европейской старины и белорусской провинциальной уюта. Сюда приезжают, чтобы насладиться историей и неспешными прогулками.	2025-08-25	## Цены\n* Съём жилья в день: примерно $30–90 за ночь (есть бюджетные варианты и несколько более дорогих отелей).\n* Ужин в ресторане (средний): примерно $15–30 на человека (в зависимости от заведения).\n\n## На территории или рядом\n* Исторический центр с замком и соборами.\n* Река Неман и набережная — прогулочные зоны, парки.\n\n## Транспорт\n* Городские автобусы (основной городской транспорт).\n* Такси и междугородние автобусы; поезд/автобус — удобный способ добраться до других городов (Минск, Брест).\n\n## Еда\n* Драники — в регионе подают местные варианты.\n* Местные варианты блюд из рыбы/картофеля и традиционные восточноевропейские салаты.	4	t
\.
COPY public.city_photos (id, city_id, url, description, "position") FROM stdin;
\.
COPY public.city_tags (city_id, tag_id, "position") FROM stdin;
\.
COPY public.collection_cities (collection_id, city_id, "position") FROM stdin;
2	1	1
2	2	2
2	3	3
2	4	0
2	5	4
2	6	5
2	7	6
2	8	7
2	9	8
2	10	9
2	11	10
3	9	1
3	13	4
3	14	5
3	15	2
3	16	9
3	17	3
3	18	8
3	19	7
3	20	6
\.
COPY public.collection_places (collection_id, place_id, "position") FROM stdin;
1	2	0
1	4	1
1	6	2
1	7	11
1	8	10
1	9	5
1	10	4
1	11	12
1	13	8
1	14	7
1	16	9
1	17	3
1	18	6
1	19	13
\.
COPY public.collection_tags (collection_id, tag_id, "position") FROM stdin;
3	1	1
2	1	1
1	5	1
4	3	1
\.
COPY public.collections (id, name, description, type, updateddate, visibility) FROM stdin;
2	Где отдохнуть: страны СНГ и ближнего зарубежья	Подборка лучших городов ближнего зарубежья для отдыха: от горных пейзажей Алматы до восточных базаров Ташкента, от старинных улочек Тбилиси до футуристических зданий Астаны. Вдохновитесь культурным разнообразием и богатой историей соседних стран!	cities	2025-07-07	t
3	Где отдохнуть в Беларуси: города и жемчужины страны	Древние замки и современные города, богатая природа и уютные местечки с уникальной атмосферой. Каждая точка — это кусочек истории, культуры или живой природы, который можно почувствовать, прогуливаясь по старинным улицам, усадьбам или тропам национальных парков. Подборка подойдёт и тем, кто ищет культурное наполнение поездки, и тем, кто хочет вдохнуть свежий воздух вековых лесов.	cities	2025-08-25	t
4	Зелёные зоны на окраине Петербурга		places	2026-08-15	t
1	Где погулять в Петербурге: зелёные зоны	Откройте для себя уютные уголки природы в Петербурге. Прогуляйтесь по зелёным аллеям, насладитесь свежим воздухом и проведите время с семьёй в живописных парках и зелёных зонах северной столицы.	places	2025-07-07	t
\.
COPY public.countries (id, name, visibility, description, updateddate, article) FROM stdin;
1	Россия	f	\N	\N	\N
2	Азербайджан	f	\N	\N	\N
3	Армения	f	\N	\N	\N
4	Беларусь	f	\N	\N	\N
5	Грузия	f	\N	\N	\N
6	Казахстан	f	\N	\N	\N
7	Кыргызстан	f	\N	\N	\N
8	Таджикистан	f	\N	\N	\N
9	Узбекистана	f	\N	\N	\N
\.
COPY public.country_tags (country_id, tag_id, "position") FROM stdin;
\.
COPY public.place_photos (id, place_id, url, description, "position") FROM stdin;
1	1	1.1.webp	\N	1
2	1	1.2.webp	\N	2
3	1	1.3.webp	\N	3
4	1	1.4.webp	\N	4
5	2	2.1.webp	\N	1
6	2	2.2.webp	\N	2
7	2	2.3.webp	\N	3
8	2	2.4.webp	\N	4
9	3	3.1.webp	\N	1
10	3	3.2.webp	\N	2
11	4	4.1.webp	\N	1
12	4	4.2.webp	\N	2
13	4	4.3.webp	\N	3
14	5	5.1.webp	\N	1
15	5	5.2.webp	\N	2
16	6	6.1.webp	\N	1
17	6	6.2.webp	\N	2
18	7	7.1.webp	\N	1
19	7	7.2.webp	\N	2
20	8	8.1.webp	\N	1
21	8	8.2.webp	\N	2
22	8	8.3.webp	\N	3
23	9	9.1.webp	\N	1
24	9	9.2.webp	\N	2
25	9	9.3.webp	\N	3
26	10	10.1.webp	\N	1
27	10	10.2.webp	\N	2
28	10	10.3.webp	\N	3
29	11	11.1.webp	\N	1
30	12	12.1.webp	\N	1
31	12	12.2.webp	\N	2
32	13	13.1.webp	\N	1
33	13	13.2.webp	\N	2
34	13	13.3.webp	\N	3
35	13	13.4.webp	\N	4
36	14	14.1.webp	\N	1
37	14	14.2.webp	\N	2
38	14	14.3.webp	\N	3
39	15	15.1.webp	\N	1
40	15	15.2.webp	\N	2
41	16	16.1.webp	\N	1
42	16	16.2.webp	\N	2
43	17	17.1.webp	\N	1
44	17	17.2.webp	\N	2
45	18	18.1.webp	\N	1
46	18	18.2.webp	\N	2
47	19	19.1.webp	\N	1
48	19	19.2.webp	\N	2
\.
COPY public.place_tags (place_id, tag_id, "position") FROM stdin;
4	1	1
13	1	1
4	4	2
\.
COPY public.places (id, name, loc, rate, description, updateddate, city_id, article, visibility) FROM stdin;
1	Пляж Озерки	\N	4.4	Живописное место у воды, идеально подходящее для отдыха на свежем воздухе и прогулки с детьми.	2025-07-01	1	\N	t
2	Шуваловский Парк	\N	4.8	Просторный лесной массив с тропинками и прудами, где можно насладиться тишиной и уединением.	2025-07-01	1	\N	t
3	Инженерный сквер	Кленовая улица	4.4	Небольшой зелёный оазис в центре города с ухоженными клумбами и скамейками для отдыха.	2025-07-01	1	\N	t
4	Парк Сосновка	\N	4.9	Один из крупнейших парков Петербурга, утопающий в соснах и идеально подходящий для прогулок и занятий спортом.	2025-07-01	1	\N	t
5	Сад Ивана Фомина	\N	4.5	Уютный сад с большим озером и приятной атмосферой.	2025-07-01	1	\N	t
6	Марсово поле	\N	4.9	Просторная зелёная площадь в центре города, популярное место для прогулок и отдыха на траве.	2025-07-01	1	\N	t
7	Парк Политехнического университета	Политехническая ул.	4.9	Тихое место с ухоженными газонами и невероятной башней, около которой приятно прогуляться или посидеть с книгой.	2025-07-01	1	\N	t
8	Парк Тихий отдых	\N	4.6	Парк на острове с уютными тропинками и лавочками, создающий атмосферу спокойствия и уюта.	2025-07-01	1	\N	t
9	Михайловский сад	\N	5.0	Элегантный сад между Спасом на Крови и Михайловским замком с ухоженными дорожками и газонами.	2025-07-01	1	\N	t
10	Летний сад	\N	5.0	Исторический парк с мраморными статуями, фонтанами и идеально ровными аллеями, олицетворяющий дух Петербурга.	2025-07-01	1	\N	t
11	Приморский парк Победы	\N	5.0	Просторный парк на Крестовском острове с живописными аллеями и фонтаном.	2025-07-01	1	\N	t
12	Екатерининский Сад	площадь Островского	5.0	Небольшой уютный сад перед Александринским театром с памятником Екатерине II, окружённый историческими зданиями.	2025-07-01	1	\N	t
13	Парк лесотехнической академии	\N	4.7	Зелёный парк с вековыми деревьями и тихими тропинками, идеальный для неспешных прогулок.	2025-07-01	1	\N	t
14	Удельный парк	\N	4.7	Обширный лесопарк на севере города, популярен среди любителей прогулок, спорта и пикников; знаменит своими тенистыми аллеями и спокойной атмосферой.	2025-07-01	1	\N	t
15	Сад Прометей	\N	4.6	Уютный сад с озером и тихой, камерной обстановкой в окружении жилых кварталов.	2025-07-01	1	\N	t
16	Александровский парк	\N	4.7	Один из старейших парков Петроградской стороны, соседствует с Петропавловской крепостью и зоопарком; благоустроенные аллеи, детские площадки и культурные объекты делают его популярным среди семей.	2025-07-01	1	\N	t
17	Сад на Пионерской площади	\N	4.9	Зелёный уголок в центре города, рядом с Театром Юных Зрителей, подходит для передышек среди городской суеты.	2025-07-01	1	\N	t
18	Юсуповский сад	\N	4.9	Живописный исторический парк с прудом и мостиками рядом с Садовой улицей; романтичное и немного скрытое место в центре города.	2025-07-01	1	\N	t
19	Никольский сад	\N	4.4	Тихий и зелёный сквер у Никольского собора, в котором приятно отдохнуть на лавочке, слушая звон колоколов.	2025-07-01	1	\N	t
\.
COPY public.tags (id, name, slug, text_color, bg_color) FROM stdin;
1	Популярное	popular	#B46D0A	#FDF4E2
3	Новинка	new	#956BD7	#F6F2FC
2	Беларусь	belarus	#FB8C55	#FEF3EE
4	Петербург	petersburg	#2794EB	#E9F4FD
5	Природа	nature	#618E41	#EEF3E9
6	Туризм	tourism	#2794EB	#E9F4FD
7	Здоровье	health	#618E41	#EEF3E9
8	Активность	activity	#FB8C55	#FEF3EE
\.
SELECT pg_catalog.setval('public.article_photos_id_seq', 3, false);
SELECT pg_catalog.setval('public.articles_id_seq', 1, true);
SELECT pg_catalog.setval('public.cities_id_seq', 21, false);
SELECT pg_catalog.setval('public.city_photos_id_seq', 1, false);
SELECT pg_catalog.setval('public.collections_id_seq', 5, true);
SELECT pg_catalog.setval('public.countries_id_seq', 10, false);
SELECT pg_catalog.setval('public.place_photos_id_seq', 48, true);
SELECT pg_catalog.setval('public.places_id_seq', 20, false);
SELECT pg_catalog.setval('public.tags_id_seq', 8, true);
ALTER TABLE ONLY public.article_photos
    ADD CONSTRAINT article_photos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.article_tags
    ADD CONSTRAINT article_tags_pkey PRIMARY KEY (article_id, tag_id);
ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.city_photos
    ADD CONSTRAINT city_photos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.city_tags
    ADD CONSTRAINT city_tags_pkey PRIMARY KEY (city_id, tag_id);
ALTER TABLE ONLY public.collection_cities
    ADD CONSTRAINT collection_cities_pkey PRIMARY KEY (collection_id, city_id);
ALTER TABLE ONLY public.collection_places
    ADD CONSTRAINT collection_places_pkey PRIMARY KEY (collection_id, place_id);
ALTER TABLE ONLY public.collection_tags
    ADD CONSTRAINT collection_tags_pkey PRIMARY KEY (collection_id, tag_id);
ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.country_tags
    ADD CONSTRAINT country_tags_pkey PRIMARY KEY (country_id, tag_id);
ALTER TABLE ONLY public.place_photos
    ADD CONSTRAINT place_photos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT place_tags_pkey PRIMARY KEY (place_id, tag_id);
ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_name_key UNIQUE (name);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_slug_key UNIQUE (slug);
ALTER TABLE ONLY public.article_tags
    ADD CONSTRAINT uq_article_tags_position UNIQUE (article_id, "position");
ALTER TABLE ONLY public.city_tags
    ADD CONSTRAINT uq_city_tags_position UNIQUE (city_id, "position");
ALTER TABLE ONLY public.collection_tags
    ADD CONSTRAINT uq_collection_tags_position UNIQUE (collection_id, "position");
ALTER TABLE ONLY public.country_tags
    ADD CONSTRAINT uq_country_tags_position UNIQUE (country_id, "position");
ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT uq_place_tags_position UNIQUE (place_id, "position");
CREATE INDEX idx_article_photos_article_id ON public.article_photos USING btree (article_id);
CREATE INDEX idx_article_tags_tag_id ON public.article_tags USING btree (tag_id);
CREATE INDEX idx_city_photos_city_id ON public.city_photos USING btree (city_id);
CREATE INDEX idx_city_tags_tag_id ON public.city_tags USING btree (tag_id);
CREATE INDEX idx_collection_tags_tag_id ON public.collection_tags USING btree (tag_id);
CREATE INDEX idx_country_tags_tag_id ON public.country_tags USING btree (tag_id);
CREATE INDEX idx_place_photos_place_id ON public.place_photos USING btree (place_id);
CREATE INDEX idx_place_tags_tag_id ON public.place_tags USING btree (tag_id);
ALTER TABLE ONLY public.article_photos
    ADD CONSTRAINT article_photos_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.article_tags
    ADD CONSTRAINT article_tags_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.article_tags
    ADD CONSTRAINT article_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id);
ALTER TABLE ONLY public.city_photos
    ADD CONSTRAINT city_photos_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.city_tags
    ADD CONSTRAINT city_tags_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.city_tags
    ADD CONSTRAINT city_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.collection_cities
    ADD CONSTRAINT collection_cities_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id);
ALTER TABLE ONLY public.collection_cities
    ADD CONSTRAINT collection_cities_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id);
ALTER TABLE ONLY public.collection_places
    ADD CONSTRAINT collection_places_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id);
ALTER TABLE ONLY public.collection_places
    ADD CONSTRAINT collection_places_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id);
ALTER TABLE ONLY public.collection_tags
    ADD CONSTRAINT collection_tags_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.collections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.collection_tags
    ADD CONSTRAINT collection_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.country_tags
    ADD CONSTRAINT country_tags_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.country_tags
    ADD CONSTRAINT country_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.place_photos
    ADD CONSTRAINT place_photos_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT place_tags_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.places(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.place_tags
    ADD CONSTRAINT place_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id);
\unrestrict hpfhfCLvJW5LEjDYgRTxLUGgI6eji5E9HuB2xk2Eo1WMcFCH9ImvmVLaZeUnkBG
