services:
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locario_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
      build:
        context: ../backend
        dockerfile: ../docker/Dockerfile.dev
      command: npm run dev
      volumes:
        - ../backend:/app
        - /app/node_modules
      ports:
        - "3000:3001"
        - "3001:3000"
      environment:
        DB_HOST: db
      depends_on:
        db:
          condition: service_healthy

  frontend:
      build:
        context: ../frontend
        dockerfile: ../docker/Dockerfile.dev
      command: npm run dev -- -H 0.0.0.0
      volumes:
        - ../frontend:/app
        - /app/node_modules
      network_mode: "service:backend"
      depends_on:
        - backend

volumes:
  postgres_data: